# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asterisk',
            fields=[
                ('uniqueid', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='uniqueid')),
                ('calldate', models.DateTimeField(db_index=True, default=b'1970-01-18 00:00:00', verbose_name='calldate')),
                ('billsec', models.IntegerField(verbose_name='BillSec')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('amaflags', models.IntegerField(verbose_name='amaflags')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('src', models.CharField(max_length=80, verbose_name='src')),
                ('dst', models.CharField(db_index=True, max_length=80, verbose_name='dst')),
                ('clid', models.CharField(max_length=80, verbose_name='clid')),
                ('channel', models.CharField(max_length=80, verbose_name='channel')),
                ('lastapp', models.CharField(max_length=80, verbose_name='lastapp')),
                ('dcontext', models.CharField(max_length=80, verbose_name='dcontext')),
                ('lastdata', models.CharField(max_length=80, verbose_name='lastdata')),
                ('linkedid', models.CharField(max_length=150, verbose_name='linkedid')),
                ('userfield', models.CharField(max_length=255, verbose_name='userfield')),
                ('dstchannel', models.CharField(max_length=80, verbose_name='dstchannel')),
                ('disposition', models.CharField(max_length=80, verbose_name='disposition')),
                ('peeraccount', models.CharField(max_length=20, verbose_name='peeraccount')),
                ('accountcode', models.CharField(db_index=True, max_length=20, verbose_name='accountcode')),
            ],
        ),
    ]
